### ISSUE TITLE
Create a new Domain for Free subscription

### ISSUE THREAD

**Issue by madhuri-muttreja** [jargon-sh/issues#1]
The button to create new domain not available for free tier. Is that normal?

**Comment by jargon-sh** [comment]
Hi @madhuri-muttreja no, that's not normal behaviour and sounds like a bug. There should be a email validation process that hasn't fired for you. I've manually validated your email though, so you should be fine to create some domains!

I'll get that bug on our backlog, thanks for raising an issue.

**Comment by jargon-sh** [comment]
This bug has been fixed now.

If anyone else has this problem, please check the email address that you signed up with for a verification email.
